name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: |
            cd code
            make
    - name: exec
      run: |
            cd code
            chmod +x main
            ./main

    - uses: actions/upload-artifact@v2
      name: upload build output
      with:
        name: main
        path: ${{ github.workspace }}/code


